### PR TITLE
Add Kubernetes with Moleculer references

### PR DESCRIPTION
**Pull request by HazemKhaled**

### CODE REVIEW

**Comment by AndreMaz** [comment]
Hey @HazemKhaled thank you very much for improving the docs. It is much appreciated.
Sorry for closing this PR but I've done substantial refactoring in the deployment page meaning that your PR can't be merged. However, I've reused everything that you wrote so thanks again :smile:

**Comment by HazemKhaled** [comment]
So you [copied my contribution](https://github.com/moleculerjs/site/commit/99c96e60793e50ef62ece8d156b30704fd14af59#diff-629a31e78f96f885d02ac4cc7f6412adR128) into master and close my pull request, you could accept my PR about K8s then do you refactor on deployment page, or request changes from my side

I invested a day comparing and validating options then share it with Moleculer community, then you copy it and remove my contribution  👎 

cc @icebob

**Comment by icebob** [comment]
Sorry, but sometimes it happens. 
When you created this PR, André has already started improving the Deployment page. So the complicated way would have been if André finished it, and your PR was conflicted with the master and you should have merged it manually into the new page (so you should work on it two times).
The easier way was what André did, merge your commit into his changes manually.

Nevertheless, this part of the docs is your contribution, just André did the merge manually instead of Github.

**Comment by AndreMaz** [comment]
Hey @HazemKhaled 
I don't want to be rude but why are you making such a big deal about 2 sentences? I said thank you (check my previous post) because you really did help.

> I invested a day comparing and validating options then share it with Moleculer community

I don't fully understand what had to be compared and validated in https://github.com/moleculerjs/site/pull/86/commits/63df4c6a971249c4a84b3c6edf55517aa32ffaea . Moreover, in two sentences I've found 3 typos `Cummunity`, `idel` and `tuotorial`. Plus, tagging syntax  (`@username`) in your commit is wrong.

Also, if you check the commit history you will see that I've been refactoring and improving docs for the v0.14 release and, by bad luck, I was working on deployment docs. So it was easier to me to use the contents of your PR.

**Comment by AndreMaz** [comment]
Again, the credit of adding kubernetes section goes all to you and to the guys that created the scripts and tutorials

**Pull request closed without merging**
