### PR TITLE
add search hotkey (`/`)

### PR DESCRIPTION
**Pull request by OutdatedVersion**
Makes it a bit easier for those focusing on their keyboard. Thank you for the inspiration, GitHub UI team.

image

### CODE REVIEW

**Review by icebob — APPROVED** [review]
Great, thanks!

**Comment by AndreMaz** [comment]
Hey @OutdatedVersion tested on Chrome and got the following result:

image

Can you fix it please?

**Comment by OutdatedVersion** [comment]
> Hey @OutdatedVersion tested on Chrome and got the following result:
> 
> 
> 
> image
> 
> 
> 
> Can you fix it please?
> 
> 

Please try without caching and let me know if it persists

**Comment by AndreMaz** [comment]
You're right 👍 Sorry

**Pull request merged**
