### PR TITLE
Add swagger-stats UI middleware example.

### PR DESCRIPTION
**Pull request by wiva-koikoi**
Use [swagger-stats UI](https://swaggerstats.io/) for quick look on the "health" of your API (TypeScript)

### CODE REVIEW

**Comment by icebob** [comment]
Why do you think, it's necessary in the moleculer-web docs?

**Comment by wiva-koikoi** [comment]
- To increase popularity and attract users it needs to provide more practical examples from real life. Users (me too :) ) like to see additional pros. After using Koa2 and FeathersJS I like the moleculer and I will be happy to see the users number growing.
- The second reason is that when I tried to setup _this_ middleware, I couldn't do it just with official swagger-stats manual and google (for FeathersJS all OK, works from half-kick). I hope this small tip will help somebody too.

**Review by icebob — APPROVED** [review]
Ok, thanks!

**Comment by saeedkhalilian** [comment]
hello. 
I want to show my visited site in graph with using swagger-stats but it didn't work . is swagger-stats work right?

**Pull request merged**
