### PR TITLE
Updated MoleculerDb documentation with latest methods

### PR DESCRIPTION
**Pull request by rzvdaniel**
Hi all,

I have updated documentation with the latest added moleculer-db methods. Should I also link the new methods to their source code in moleculer-db repository?

Best,
Razvan

### CODE REVIEW

**Comment by icebob** [comment]
Thanks @rzvdaniel 
@AndreMaz please review, but wait with merge while this changes in moleculer-db is not published on NPM.

**Comment by AndreMaz** [comment]
@rzvdaniel that was fast :smile: Thanks

Regarding the links, I really don't know whether we should keep them or completely remove them all.
I've added them because many times newcomers asked "how method A (or B) works exactly?"... So I've thought that docs + link to method would help them. However, due to code updates/improvements, the links are no longer pointing at right places. (I've used links instead of permalinks to avoid pointing to old code).

@rzvdaniel @icebob what do you think? Should we keep them or not?

**Comment by rzvdaniel** [comment]
Hi all!
As @icebob suggested in Discord chat, I will let the new documentation as is (without links pointing to the source code).

"I think would be better to remove all other links because it didn't & won't be updated correctly.
Too much work to keep sync the link with the source code." - @icebob

Best!

**Comment by AndreMaz** [comment]
Ok. Problem solved.

@rzvdaniel can you please remove the links?

**Comment by icebob** [comment]
Package is published.

**Pull request merged**
