### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by icebob**
Enjoy!

### CODE REVIEW

**Comment by intech** [comment]
wow! I need Russian files for start translating by community =)

**Comment by icebob** [comment]
@intech Sure, but currently I'm getting acquinted with crowdin :) and at first I have to find out how I organize the docs files in the repo to support multiple languages (currently structure doesn't support it.

**Comment by intech** [comment]
> @intech Sure, but currently I'm getting acquinted with crowdin :) and at first I have to find out how I organize the docs files in the repo to support multiple languages (currently structure doesn't support it.

@icebob I found out to maintain the site further
/source/_data/languages.yml
Снимок экрана от 2019-09-26 17-14-54

and after 
Снимок экрана от 2019-09-26 17-13-54

in config.yml
```
language:
  - ru
  - en
```
default path:
```yaml
i18n_dir: :lang
```
https://hexo.io/docs/internationalization.html#Path

Url https://moleculerjs.com/ru/api

**Comment by icebob** [comment]
I see, just there is the version number in the path which can be before or after. If the language is before language, it means all versions will be one project on crowdin and it will show poor percentage if we don't translate all old version docs, as well and I think it is not neccessary. Would be enough the 0.14.

If the version is before language (`docs/0.14/ru/`), I should add the new folders when a new version released and maybe we can't copy the translated text from the docs of previous version into the new version.

So first of all, I should test these cases in an example repo. I think the hexo configuration will be the easiest part of it :)

**Comment by icebob** [comment]
@intech Crowdin has a "pre-translate" feature which translates the files with an online translator. Could you check that it can help you or better to translate from English directly?
Example russian translated broker.md file: [broker.zip](https://github.com/moleculerjs/site/files/3665974/broker.zip)

**Comment by intech** [comment]
> @intech Crowdin has a "pre-translate" feature which translates the files with an online translator. Could you check that it can help you or better to translate from English directly?
> Example russian translated broker.md file: [broker.zip](https://github.com/moleculerjs/site/files/3665974/broker.zip)

will need to check and fix a lot, 20% of everything is suitable

**Comment by AndreMaz** [comment]
@intech Hacktoberfest 2019 is starting in a few days. Maybe you can ask russian community to help translating.
3 PRs with translations = 1 free t-shirt plus stickers is a great deal 😄

**Comment by intech** [comment]
@AndreMaz t-shirt is cool) But I planned to finance the translation of moleculer documentation into Russian with the help of professional translators. This is my contribution to the development of the project :)

**Comment by AndreMaz** [comment]
Holy shit! That would be amazing 😃

**Comment by icebob** [comment]
Awesome @intech! So I won't use pre-translate, leave all files in English before translating.
At weekend I've improved the repo to support multi languages. Now I'm starting to check all 0.14 docs in English that everything is correct and when I'm ready, I will add them to Crowding and I will write you when you can start it, right?

**Comment by icebob** [comment]
@AndreMaz the problem is that we can't push translations as a PR because Crowdin will do it automatically.

**Comment by intech** [comment]
@icebob sounds like a good plan!

**Pull request closed without merging**
